name: json_file_generator
description: Load and save file using json
version: 1.0.0+1
homepage: https://github.com/gmvbr/json_file
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: '>=2.1.0 <4.0.0'
  build: ^2.2.1
  build_config: ^1.0.0
  source_gen: any
  json_file:
    git:
      url: git://github.com/gmvbr/json_file.git
      path: json_file
  